Repository Leets-Official/EatMate-BE, pull requests merged in 2025-02, with the labels that each got.

#148 [fix] 누락된 필드값 및 엔티티 수정
  src/main/java/com/example/eatmate/app/domain/meeting/domain/DeliveryMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpdateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/test/java/com/example/eatmate/app/domain/meeting/service/MeetingServiceTest.java
Labels: add, 현수

#156 [add] 모임 조회시 response 추가
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MyMeetingListResponseDto.java
Labels: add, 현수

#163 [add] 채팅방 입장시 dto에 유저 정보 추가
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomResponseDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
Labels: add, 동윤

#168 [mod] 프로필 수정 로직 일부 수정
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
Labels: mod, 석준

#161 [Refactor] ReportType 값이 유효하지 않은 경우 검증 추가
  src/main/java/com/example/eatmate/app/domain/report/domain/ReportType.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: refactor, 시현

#169 [refactor] 채팅방 입장 실시간성 문제 수정
  src/main/java/com/example/eatmate/app/domain/chat/controller/ChatController.java
  src/main/java/com/example/eatmate/app/domain/chat/dto/response/ChatMessageResponseDto.java
  src/main/java/com/example/eatmate/app/domain/chat/service/ChatService.java
  src/main/java/com/example/eatmate/app/domain/chat/service/WebSocketEventListener.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatMemberListDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/event/NoticeMemberLeftEvent.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/app/domain/meeting/listener/MeetingEventListener.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtHandshakeInterceptor.java
  src/main/java/com/example/eatmate/global/config/WebSocketConfig.java
Labels: refactor, 동윤

#172 [fix] 171 프로필 이미지 널포인터 익셉션 해결
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomResponseDto.java
Labels: fix, 동윤

#170 [docs] readme 작성
  README.md
Labels: docs, 현수

#179 [mod] 모임 수정 및 모임 상세 조회 수정
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomResponseDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/DeliveryMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/Meeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/MeetingBackgroundType.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/OfflineMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateOfflineMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpdateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpdateOfflineMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
Labels: mod, 현수

#182 [hotfix] #181 health check 추가
  src/main/java/com/example/eatmate/global/common/controller/StatusCheckController.java
Labels: hotfix, 시현

#187 [refactor] 임박한 모임 조회 dto 수정
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingParticipantRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpcomingMeetingResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpcomingMeetingResultDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
Labels: refactor, 동윤

#189 [config] #188 컨테이너의 최대 메모리를 1.5GB로 수정
  .github/workflows/dev.yml
Labels: add, fix, 시현
