Repository Leets-Official/EatMate-BE, pull requests merged in 2025-01, with the labels that each got.

#5 [feat] 모임 생성참여 구현
  .github/workflows/dev.yml
  build.gradle
  build/reports/tests/test/classes/com.example.eatmate.EatmateApplicationTests.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/com.example.eatmate.html
  build/resolvedMainClassName
  build/test-results/test/TEST-com.example.eatmate.EatmateApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileTestJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/DeliveryMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/FoodCategory.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/GenderRestriction.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/Meeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/MeetingParticipant.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/OfflineMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/OfflineMeetingCategory.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/ParticipantLimit.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/ParticipantRole.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/DeliveryMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingParticipantRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/OfflineMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateDeliveryMeetingResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateOfflineMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateOfflineMeetingResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/DeliveryMeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/DeliveryMeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/OfflineMeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/OfflineMeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/app/domain/member/controller/MemberController.java
  src/main/java/com/example/eatmate/app/domain/member/domain/BirthDate.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Gender.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Mbti.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Role.java
  src/main/java/com/example/eatmate/app/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MemberSignUpRequestDto.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/global/auth/login/service/CustomUserDetails.java
  src/main/java/com/example/eatmate/global/config/SecurityConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
  src/test/java/com/example/eatmate/app/domain/meeting/service/MeetingServiceTest.java
Labels: feat, 현수

#8 [Fix] 회원가입 로그인 로직 오류수정
  src/main/java/com/example/eatmate/app/domain/member/domain/Mbti.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
  src/main/java/com/example/eatmate/app/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MemberSignUpRequestDto.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2User.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
Labels: fix, 석준

#13 [Chore] #12 pr에서는 빌드만 실행되도록 수정
  .github/workflows/dev.yml
Labels: chore, 시현

#10 [fix] 모임 관련 기능 오류 수정
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/MeetingParticipant.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingParticipantRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateOfflineMeetingResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/DeliveryMeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/DeliveryMeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/OfflineMeetingDetailResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/OfflineMeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/app/domain/member/controller/MemberController.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MemberLoginRequestDto.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MemberLoginResponseDto.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
  src/main/java/com/example/eatmate/global/auth/login/service/CustomUserDetails.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/test/java/com/example/eatmate/app/domain/meeting/service/MeetingServiceTest.java
Labels: feat, fix, 현수

#11 [Feat] 회원 신고 구현
  src/main/java/com/example/eatmate/app/domain/member/domain/Role.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/app/domain/report/controller/ReportAdminController.java
  src/main/java/com/example/eatmate/app/domain/report/controller/ReportController.java
  src/main/java/com/example/eatmate/app/domain/report/converter/ReportTypeListConverter.java
  src/main/java/com/example/eatmate/app/domain/report/domain/Report.java
  src/main/java/com/example/eatmate/app/domain/report/domain/ReportType.java
  src/main/java/com/example/eatmate/app/domain/report/domain/repository/ReportRepository.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportAdminResponseDto.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportResponseDto.java
  src/main/java/com/example/eatmate/app/domain/report/service/ReportService.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/example/eatmate/global/config/SecurityConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat, 시현

#21 [Fix] 회원가입 쿠키 방식 적용
  src/main/java/com/example/eatmate/global/auth/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/example/eatmate/global/config/SecurityConfig.java
Labels: fix, 석준

#24 [Feat] 사용자 정보 반환 api 구현
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
  src/main/java/com/example/eatmate/global/auth/login/dto/UserLoginResponseDto.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/example/eatmate/global/auth/login/service/LoginService.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat, 석준

#19 [Feat] 공지사항 기능 구현
  src/main/java/com/example/eatmate/app/domain/notice/controller/NoticeAdminController.java
  src/main/java/com/example/eatmate/app/domain/notice/controller/NoticeController.java
  src/main/java/com/example/eatmate/app/domain/notice/domain/Notice.java
  src/main/java/com/example/eatmate/app/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/example/eatmate/app/domain/notice/dto/NoticeAdminRequestDto.java
  src/main/java/com/example/eatmate/app/domain/notice/dto/NoticeIdResponseDto.java
  src/main/java/com/example/eatmate/app/domain/notice/dto/NoticeResponseDto.java
  src/main/java/com/example/eatmate/app/domain/notice/service/NoticeService.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat, 시현

#25 [feat] 모임 추가기능 구현
  build.gradle
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/Meeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/MeetingStatus.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/DeliveryMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/OfflineMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpcomingMeetingResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/config/QueryDslConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
  src/main/java/com/example/eatmate/global/response/CursorResponseDto.java
Labels: feat, 현수

#27 [feat] 예외처리 자동화
  src/main/java/com/example/eatmate/app/domain/meeting/domain/MeetingStatus.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
  src/main/java/com/example/eatmate/global/auth/login/dto/UserLoginResponseDto.java
  src/main/java/com/example/eatmate/global/auth/login/service/LoginService.java
  src/main/java/com/example/eatmate/global/config/RestTemplateConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GithubIssueGenerator.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
  src/main/java/com/example/eatmate/global/config/error/exception/dto/IssueCreateRequestDto.java
  src/test/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandlerTest.java
Labels: feat, 현수

#35 [fix] NoResourceFoundException 예외 처리 추가
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
Labels: fix, 현수

#53 [Feat] S3 버킷 연결
  .github/workflows/dev.yml
  build.gradle
  src/main/java/com/example/eatmate/app/domain/image/domain/Image.java
  src/main/java/com/example/eatmate/app/domain/image/domain/ImageType.java
  src/main/java/com/example/eatmate/app/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/example/eatmate/app/domain/image/service/ImageSaveService.java
  src/main/java/com/example/eatmate/global/config/S3Config.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat

#52 Feat/#14 회원 관련 기능 구현
  src/main/java/com/example/eatmate/app/domain/member/controller/MemberController.java
  src/main/java/com/example/eatmate/app/domain/member/domain/BirthDate.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MyInfoResponseDto.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MyInfoUpdateRequestDto.java
  src/main/java/com/example/eatmate/app/domain/member/dto/UserInfoResponseDto.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
Labels: feat, 석준

#69 [feat] 모임 필터링정렬 기능 추가
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingSortType.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/MyMeetingListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/common/util/SecurityUtils.java
  src/main/java/com/example/eatmate/global/common/util/StringToEnumConverterFactoryUtils.java
  src/main/java/com/example/eatmate/global/config/WebConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/response/CursorInfo.java
  src/main/java/com/example/eatmate/global/response/CursorResponseDto.java
Labels: feat, 현수

#68 [Add] 프로필 사진 필드 추가
  src/main/java/com/example/eatmate/app/domain/member/controller/MemberController.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
  src/main/java/com/example/eatmate/app/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MemberSignUpRequestDto.java
  src/main/java/com/example/eatmate/app/domain/member/dto/MyInfoResponseDto.java
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
Labels: add, 석준

#71 [Feat] 차단 기능 구현
  src/main/java/com/example/eatmate/app/domain/block/controller/BlockController.java
  src/main/java/com/example/eatmate/app/domain/block/domain/Block.java
  src/main/java/com/example/eatmate/app/domain/block/domain/repository/BlockRepository.java
  src/main/java/com/example/eatmate/app/domain/block/dto/BlockIdResponseDto.java
  src/main/java/com/example/eatmate/app/domain/block/dto/BlockMemberRequestDto.java
  src/main/java/com/example/eatmate/app/domain/block/dto/BlockMemberResponseDto.java
  src/main/java/com/example/eatmate/app/domain/block/service/BlockService.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat, 시현

#84 [Feat] 차단한 유저 있는 모임 참여 불가 구현
  src/main/java/com/example/eatmate/EatmateApplication.java
  src/main/java/com/example/eatmate/app/domain/block/domain/repository/BlockRepository.java
  src/main/java/com/example/eatmate/app/domain/chat/service/ChatService.java
  src/main/java/com/example/eatmate/app/domain/chat/service/QueueManager.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/BankName.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/DeliveryMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/OfflineMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/app/domain/member/domain/Mbti.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2User.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/GoogleOAuthUserInfo.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginFailureHandler.java
  src/main/java/com/example/eatmate/global/auth/login/service/LoginService.java
  src/main/java/com/example/eatmate/global/common/BaseTimeEntity.java
  src/main/java/com/example/eatmate/global/config/RabbitConfig.java
  src/main/java/com/example/eatmate/global/config/WebSocketConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/custom/InvalidMbtiException.java
  src/main/java/com/example/eatmate/global/config/error/exception/custom/InvalidTokenException.java
  src/main/java/com/example/eatmate/global/config/error/exception/custom/MemberAlreadyExistsException.java
  src/main/java/com/example/eatmate/global/config/error/exception/custom/UserNotFoundException.java
  src/main/java/com/example/eatmate/global/config/swagger/SwaggerConfig.java
Labels: feat, 현수

#81 [fix] 모임 목록 조회 오류 수정
  src/main/java/com/example/eatmate/app/domain/meeting/controller/MeetingController.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/example/eatmate/global/response/CursorInfo.java
Labels: fix, 현수

#82 [add] GENDER 필드 토큰에 추가
  src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
  src/main/java/com/example/eatmate/global/auth/login/dto/UserLoginResponseDto.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2User.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/example/eatmate/global/auth/login/service/LoginService.java
Labels: add, 석준

#83 [feat] 실시간 채팅과 모임 연동 구현
  src/main/java/com/example/eatmate/app/domain/chat/controller/ChatController.java
  src/main/java/com/example/eatmate/app/domain/chat/domain/Chat.java
  src/main/java/com/example/eatmate/app/domain/chat/domain/repository/ChatRepository.java
  src/main/java/com/example/eatmate/app/domain/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/example/eatmate/app/domain/chat/service/ChatService.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/domain/ChatRoom.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/domain/DeletedStatus.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/domain/repository/ChatRoomRepository.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatMemberDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomDeliveryNoticeDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomOfflineNoticeDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomResponseDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/event/HostChatRoomLeftEvent.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/event/ParticipantChatRoomLeftEvent.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/listener/ChatRoomEventListener.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/config/WebSocketConfig.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: feat, 동윤

#97 [mod] swaggerConfig 수정
  src/main/java/com/example/eatmate/global/config/swagger/SwaggerConfig.java
Labels: mod, 석준

#99 [Refactor] 회원 신고 로직 수정
  src/main/java/com/example/eatmate/app/domain/report/controller/ReportController.java
  src/main/java/com/example/eatmate/app/domain/report/converter/ReportTypeListConverter.java
  src/main/java/com/example/eatmate/app/domain/report/domain/Report.java
  src/main/java/com/example/eatmate/app/domain/report/domain/ReportType.java
  src/main/java/com/example/eatmate/app/domain/report/domain/repository/ReportRepository.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportAdminResponseDto.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportMemberListResponseDto.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/eatmate/app/domain/report/dto/ReportResponseDto.java
  src/main/java/com/example/eatmate/app/domain/report/service/ReportService.java
Labels: refactor, 시현

#100 [feat] 동시성 문제 및 일정기간 후 모임 삭제 기능 추가
  build.gradle
  src/main/java/com/example/eatmate/EatmateApplication.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/DeliveryMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/OfflineMeeting.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/DeliveryMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/MeetingParticipantRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/domain/repository/OfflineMeetingRepository.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/CreateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpdateDeliveryMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/dto/UpdateOfflineMeetingRequestDto.java
  src/main/java/com/example/eatmate/app/domain/meeting/scheduler/MeetingStatusScheduler.java
  src/main/java/com/example/eatmate/app/domain/meeting/service/MeetingService.java
  src/main/java/com/example/eatmate/global/config/AsyncConfig.java
  src/main/java/com/example/eatmate/global/config/error/exception/GithubIssueGenerator.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
  src/test/java/com/example/eatmate/app/domain/meeting/scheduler/MeetingStatusSchedulerTest.java
  src/test/java/com/example/eatmate/app/domain/meeting/service/MeetingServiceTest.java
Labels: feat, 현수

#127 [fix] 예외 해결
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
  src/main/java/com/example/eatmate/global/config/error/exception/GlobalExceptionHandler.java
Labels: fix, 현수

#112 [refactor] chatroomresponsedto 일부 수정
  src/main/java/com/example/eatmate/app/domain/chat/controller/ChatController.java
  src/main/java/com/example/eatmate/app/domain/chat/domain/repository/ChatRepository.java
  src/main/java/com/example/eatmate/app/domain/chat/dto/response/ChatMessageListDto.java
  src/main/java/com/example/eatmate/app/domain/chat/service/ChatService.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/dto/response/ChatRoomResponseDto.java
  src/main/java/com/example/eatmate/app/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
Labels: refactor, 동윤
